# default Profile
spring:
  profiles:
    active: "build"
---
# build config
spring:
  config:
    activate:
      on-profile: "build"
  datasource:
    url: "jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul"
    username: test
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: true
  data:
    redis:
      host: localhost
      port: 6380
---
# local config
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: "jdbc:mysql://local-db:3306/test?serverTimezone=Asia/Seoul"
    username: local
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  data:
    redis:
      host: redis
      port: 6379
---
# prod config
spring:
  config:
    activate:
      on-profile: "prod"
  datasource:
    url: jdbc:mysql://db:3306/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  data:
    redis:
      host: redis
      port: 6379