name: cd

on: [ pull_request ]

jobs:
  push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Take tag version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      #      - name: backend environment setting
      #        run: |
      #          touch .env.production
      #          echo -e ${{ secrets.BACKEND_PRODUCTION_ENVIRONMENT }} > .env.production

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker registry login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.access_token }}

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew bootJar

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/github-actions-test:latest
            ghcr.io/${{ github.repository_owner }}/github-actions-test:${{ steps.tag_version.outputs.new_tag }}
          push: true

  cd:
    needs: [push-docker-image]
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: copy docker compose & config file into production server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: './docker-compose.prod.yml,./script/deploy.sh'#,backend/nginx/prod/nginx.conf,
          target: 'github-actions-test'

      - name: deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd github-actions-test
            sudo chmod +x ./script/deploy.sh
            ./script/deploy.sh